title: Bells Shells
email: ""
description: >-
  A one-page personal site for Bells Shells.
baseurl: "" # the subpath of your site, e.g. /repo-name
url: "" # the production url, e.g. https://bells-shells.github.io
markdown: kramdown
permalink: pretty
